name: example
description: An example usage of the AnimatedFlightPaths package.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  animated_flight_paths:
    path: ../
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
